version: "3.7"
services:
  ultrashub-db:
    image: postgres
    restart: always
    container_name: ultrashub-postgres
    ports:
      - 5433:5432
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
